version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:latest
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --
    environment:
      DGRAPH_ALPHA_SECURITY: whitelist=0.0.0.0/0
      DGRAPH_ALPHA_LIMIT: mutations-nquad=9000000;